server:
  port: 8083
  servlet:
    context-path: /

#spring:
#  redis:
#    host:
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 500
#        min-idle: 0
#    lettuce:
#      shutdown-timeout: 0ms



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    url: redis://wqy123456@192.168.***.***:6379
    ssl: false
    timeout: 1000
    jedis:
      pool:
        max-active: 1000
        max-wait: 100s
        max-idle: 1000
        min-idle: 1000
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: embedded
    properties:
      org:
        quartz:
          dataSource:
            quartzDataSource:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
              user: root
              password:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

#spring:
#  redis:
#    database: 0
#    url: redis://192.168.**.***:6379
#    password:
#    ssl: false
#    timeout: 1000
#    jedis:
#      pool:
#        max-active: 1000
#        max-wait: 100s
#        max-idle: 1000
#        min-idle: 1000

